### ISSUE TITLE
Inconsistent file names on file system vs require statement

### ISSUE THREAD

**Issue by dzoba** [donavon/react-wobbly-spinner#4]
Hi there,

I am unable to use react-wobbly-spinner in my project because the latest version on NPM has file name capitalization issues.  See this screenshot:

![image](https://cloud.githubusercontent.com/assets/857664/16391761/6d235b10-3c5d-11e6-9c11-e954967c7733.png)

I was going to make a PR but I don't see this issue when I clone and build this repo, so I think there may be some discrepancy between what is on Github and the latest version on npm.

**Comment by donavon** [comment]
Thx! I'll take a look.

**Comment by donavon** [comment]
I published 1.1.0. It should work now. I also updated the codepen to use the latest from NPM and it works.

**Comment by dzoba** [comment]
Awesome, thank you!
